# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      PORT: 5005
      API_KEY: '12345-xyx'
      GITHUB_USER: "@danielebarbaro"
      API_NOTES_KEY: "s935mb-922676-mzr"
      API_NOTES_LINK: "https://its.dbdevelopment.tech/notes"
      API_KEY_LINK: "https://its.dbdevelopment.tech/key"

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
